# 3. 파이토치 기초

In [2]:
import torch

In [6]:
import numpy as np
def print_val(x):
    print "Type: ", type(x)
    print "Shape:" , x.shape
    print "값: \n", x
    print " "

In [7]:
x=torch.rand(2,3,2)  # uniform: 0~1사이 모든 값들이 나올 확률이 같다.
print_val(x)

x=torch.randn(2,3)  # Gaussian: 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값
print_val(x)

Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 3, 2])
값: 
tensor([[[0.9215, 0.1246],
         [0.6482, 0.1300],
         [0.9944, 0.1800]],

        [[0.9922, 0.9542],
         [0.3257, 0.9698],
         [0.9674, 0.7312]]])
 
Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
tensor([[ 0.4724,  0.5023,  1.2266],
        [ 3.1838,  0.3897, -0.7361]])
 


In [8]:
x=torch.randperm(4)  # 0 ~ n-1까지 값을 원소로 갖는 배열->랜덤 배열
##여기서는 0~3이 랜덤하게 들어간다.
print_val(x)

Type:  <class 'torch.Tensor'>
Shape: torch.Size([4])
값: 
tensor([1, 2, 0, 3])
 


In [10]:
# [start, end] 구간을 step 단위로 나누어서 배열로 생성
x=torch.arange(0,3,step=0.5)  #0부터, 3까지, 0.5 단위로 나눈다. 0이상 3미만
print_val(x)

Type:  <class 'torch.Tensor'>
Shape: torch.Size([6])
값: 
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
 


In [12]:
print_val(torch.ones(3,4))   #(3,4) 배열, 1로 채운다
print_val(torch.zeros(3,4))  #(3,4) 배열, 0으로 채운다

Type:  <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 
Type:  <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
 


In [18]:
print_val(torch.Tensor(2,4))  #(2,4) 배열, 적당한 쓰레기 값으로 채운다

print_val(torch.Tensor([2,3]))  #[] 이용하여 차원 늘리기
print_val(torch.Tensor([[2,3],[3,4]]))

Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 4])
값: 
tensor([[3.6029e+15, 4.5785e-41, 6.9810e+14, 4.5785e-41],
        [1.4566e+21, 4.5785e-41, 9.5129e+26, 4.5785e-41]])
 
Type:  <class 'torch.Tensor'>
Shape: torch.Size([2])
값: 
tensor([2., 3.])
 
Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
값: 
tensor([[2., 3.],
        [3., 4.]])
 


In [19]:
#텐서 타입 변환하기
x=torch.FloatTensor(2,3) #float로 바꾸기(좀 더 복잡한 값)
print_val(x)

x=x.type_as(torch.IntTensor()) #다시 int tensor로 바꾸기
print_val(x)

Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
tensor([[1.6202e+15, 4.5785e-41, 1.6202e+15],
        [4.5785e-41, 1.6202e+15, 4.5785e-41]])
 
Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
tensor([[-2147483648,           0, -2147483648],
        [          0, -2147483648,           0]], dtype=torch.int32)
 


In [23]:
# 텐서 크기 반환
torch.FloatTensor(3,4,5).size() ##shape랑 비슷함

torch.Size([3, 4, 5])

In [25]:
#numpy array -> torch tensor
import numpy as np
np_x=np.ndarray((2,3),dtype=int) ## (2,3)shape 갖도록 배열 선언, int 
print_val(np_x)

x=torch.from_numpy(np_x) ##numpy array를 torch tensor로 바꿈
print_val(x) ##값은 바뀌지 않지만 데이터의 타입이 바뀜, GPU 올라가기 위해서 필요!!

Type:  <type 'numpy.ndarray'>
Shape: (2, 3)
값: 
[[140331268741240 140331268741240 140329099739232]
 [140331078015496 140331067947264  94576671592816]]
 
Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
tensor([[140331268741240, 140331268741240, 140329099739232],
        [140331078015496, 140331067947264,  94576671592816]])
 
